### ISSUE TITLE
Example doesn't work anymore

### ISSUE THREAD

**Issue by davidefabbri** [Pagawa/PgwSlider#17]
Example on page http://pgwjs.com/pgwslider/ doesn't work anymore

**Comment by jonathan-piat** [comment]
Hello davidefabbri,

Thanks for your report, the issue has been fixed.
Sorry for the inconvenience.

## 

Jonathan

**Comment by davidefabbri** [comment]
Hello jonathan-plat,
thanks,you've been very quick.

Great job!

Davide
