### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by AnaCamelo** [Pagawa/PgwSlider#19]
Hi, sorry for asking this, but I'd like to know something:

Once I download the .zip here, how should I organize the files (folders) and link them into the HTML file?

I have placed the pgwslider.css file on the css folder, and the pgwslider.min.js in the js folder. Additionally, I created a custom.js and included the code 

$(document).ready(function() {
    $('.pgwSlider').pgwSlider();
});

But I dont know where the other files should go and where should I link them to the HTML file, so what i see now is this: 

![captura de pantalla 2015-04-14 a las 11 16 18 a m](https://cloud.githubusercontent.com/assets/11947872/7142968/1a831aa0-e2a2-11e4-8b82-c15bc3b02eb3.png)

I'd really appreciate some help with this. Thanks a lot!!

**Comment by rowman25** [comment]
DId you ever get this working?  I am having the same issues.

**Comment by AnaCamelo** [comment]
It never worked :S. I had to create a whole new code :/

**Comment by jonathan-piat** [comment]
The plugin works: http://pgwjs.com/pgwslider/
Looking on your side.
